---
# Changes here will be overwritten by Copier
_commit: c804bf3
_src_path: git@github.com:datarobot/af-component-base.git
copyright_year: 2025
github_owner_group: '@datarobot/buzok'
harness_org_id: No_Code_Apps
include_core: false
oss_repo_name: datarobot-agent-templates
private_repo_name: recipe-datarobot-agent-templates
template_code_name: datarobot-agent-templates
template_description: This is a template for DataRobot Agents.
template_name: DataRobot Agent Templates
